export const sampleFeedback: string[] = [
  "Need dark mode so I can work late without eye strain.",
  "Dark mode missing is the main reason my team still uses a competitor.",
  "Please add a dark theme for the dashboard and settings pages.",
  "The app is too bright during evening incident reviews.",
  "A night mode toggle would make the product feel much more polished.",
  "Dark theme should apply to charts, modals, and emails previews.",
  "I keep looking for dark mode in preferences and cannot find it.",
  "Our designers asked whether dark mode is on the roadmap.",
  "The white UI hurts on long planning sessions. Dark mode please.",
  "Please add automatic dark mode based on my operating system.",
  "Dark mode support would help our support team on night shifts.",
  "The editor needs a dark theme for writing release notes.",
  "I love the product, but no dark mode feels dated.",
  "Dark mode missing makes demos look less premium.",
  "Can you add dark theme to the mobile app too?",
  "We need dark mode for accessibility and low-light work.",
  "The contrast in the bright theme is hard after a full day.",
  "Dark mode is the most requested feature in our internal rollout.",
  "Please ship a dark theme before our company-wide launch.",
  "Night mode would make reviewing feedback much easier.",
  "Offline support is needed when I travel for customer meetings.",
  "I cannot access notes on flights because the app has no offline mode.",
  "Please add offline mode for field sales teams.",
  "The product becomes useless when hotel Wi-Fi drops.",
  "I need to draft updates offline and sync later.",
  "Offline support would help our consultants on trains.",
  "Can I keep using boards without an internet connection?",
  "The mobile app should cache recent workspaces for offline access.",
  "Offline mode for travel is a must-have for our executives.",
  "I lose momentum when the app blocks me while offline.",
  "Please let me read customer feedback offline.",
  "We need offline drafts for long flights.",
  "Offline-first notes would make this viable for our field teams.",
  "The app should queue changes and sync once I reconnect.",
  "I need a clear indicator when work is saved locally offline.",
  "Offline access to sprint plans would be very valuable.",
  "The app should not show a blank screen with no connection.",
  "Please cache the last project so I can keep working offline.",
  "Offline mode is required before we can expand usage to sales.",
  "Being unable to work offline is our biggest adoption blocker.",
  "Sync is very slow after editing a large backlog.",
  "Changes take too long to appear for teammates.",
  "The sync spinner stays active for minutes on busy projects.",
  "Please improve real-time sync between browser tabs.",
  "I edited a ticket and my teammate did not see it until refreshing.",
  "Sync conflicts are confusing and sometimes duplicate comments.",
  "The board feels unreliable because updates lag behind.",
  "Please make sync faster for large customer feedback imports.",
  "We had duplicate tasks after two people edited the same item.",
  "The sync status is unclear and makes me nervous.",
  "Real-time collaboration needs to feel instant.",
  "The app sometimes overwrites edits after reconnecting.",
  "Backlog updates should sync in seconds, not minutes.",
  "I keep refreshing the page to confirm whether sync finished.",
  "Sync failures need clearer error messages.",
  "Comments show up late during planning meetings.",
  "Importing feedback blocks the app while sync catches up.",
  "Please add conflict resolution for simultaneous edits.",
  "The slow sync makes standup prep frustrating.",
  "Our team lost trust after sync duplicated several requests.",
  "The dashboard loads slowly with a few thousand reviews.",
  "Search performance is sluggish on larger accounts.",
  "The app feels laggy when switching between projects.",
  "Charts take too long to render after importing feedback.",
  "Please improve performance on the priorities page.",
  "Typing in the feedback textarea has noticeable delay.",
  "The initial load time is too slow for daily use.",
  "Filtering themes freezes the browser for several seconds.",
  "The app gets sluggish after uploading a CSV.",
  "Performance drops badly when I open the sprint plan tab.",
  "The backlog page should load under two seconds.",
  "Large workspaces make the UI stutter.",
  "Please optimize the import flow. It hangs on bigger files.",
  "The app uses too much memory in long sessions.",
  "Scrolling through feedback items is choppy.",
  "The dashboard should feel faster during demos.",
  "Exporting issues is slow and blocks everything else.",
  "The product needs better loading performance on mobile.",
  "Theme clustering takes too long for high-volume feedback.",
  "The UI becomes unresponsive while calculating priorities.",
  "The mobile app needs push notifications for assigned issues.",
  "Please add a better mobile review experience.",
  "I need to approve sprint plans from my phone.",
  "The mobile layout is cramped on smaller screens.",
  "Can you add swipe actions for triaging feedback on mobile?",
  "The iOS app should support quick comments.",
  "Android users need the same features as the web app.",
  "Mobile search is hard to use with long feedback lists.",
  "Please add mobile notifications when priorities change.",
  "The app should let managers review GitHub issues on mobile.",
  "I want a compact mobile view for standup.",
  "The mobile app should support uploading screenshots.",
  "It is hard to read engineering plans on my phone.",
  "Please improve mobile navigation between tabs.",
  "Feature voting should work better on mobile.",
  "The mobile keyboard covers important input fields.",
  "I need a mobile-friendly way to load sample customer data.",
  "Please add share links that open cleanly in mobile.",
  "The mobile app should support offline reading too.",
  "Mobile polish would help adoption with executives."
];

export function getSampleFeedbackText() {
  return sampleFeedback.join("\n");
}
